"""Document upload, parsing, and chunk management module."""

from .document_api import DocumentRagflowAPI
from .document_dto import (
    ChangeStatusRequest,
    CreateChunkRequest,
    DeleteChunksRequest,
    DeleteDocumentsRequest,
    DocumentInfosRequest,
    ListChunksRequest,
    ListDocumentsRequest,
    MetadataSummaryRequest,
    RunDocumentRequest,
    SetMetadataRequest,
    ThumbnailsRequest,
    UploadDocumentRequest,
    # New Request DTOs
    WebCrawlRequest,
    CreateDocumentRequest,
    RenameDocumentRequest,
    ChangeParserRequest,
    UpdateMetadataSettingsRequest,
    GetFiltersRequest,
    BatchUpdateMetadataRequest,
    GetChunkRequest,
    UpdateChunkRequest,
    SwitchChunkRequest,
    # Response DTOs
    CreateDocumentResponse,
    UpdateMetadataSettingsResponse,
    GetFiltersResponse,
    BatchUpdateMetadataResponse,
    GetChunkResponse,
    ListDocumentsResponse,
    ListChunksResponse,
    UploadDocumentResponse,
)

__all__ = [
    "DocumentRagflowAPI",
    "UploadDocumentRequest",
    "RunDocumentRequest",
    "ChangeStatusRequest",
    "DocumentInfosRequest",
    "MetadataSummaryRequest",
    "ListDocumentsRequest",
    "DeleteDocumentsRequest",
    "ListChunksRequest",
    "CreateChunkRequest",
    "DeleteChunksRequest",
    "ThumbnailsRequest",
    "SetMetadataRequest",
    # New Request DTOs
    "WebCrawlRequest",
    "CreateDocumentRequest",
    "RenameDocumentRequest",
    "ChangeParserRequest",
    "UpdateMetadataSettingsRequest",
    "GetFiltersRequest",
    "BatchUpdateMetadataRequest",
    "GetChunkRequest",
    "UpdateChunkRequest",
    "SwitchChunkRequest",
    # Response DTOs
    "CreateDocumentResponse",
    "UpdateMetadataSettingsResponse",
    "GetFiltersResponse",
    "BatchUpdateMetadataResponse",
    "GetChunkResponse",
    "ListDocumentsResponse",
    "ListChunksResponse",
    "UploadDocumentResponse",
]
